### ISSUE TITLE
Double callback prevention shouldn't be needed in bootstrap

### ISSUE THREAD

**Issue by chvck** [couchbase/gocbcorex#84] opened 2023-04-12 06:42 UTC
We use an atomic to prevent bootstrap from being able to callback twice. This shouldn't be necessary and is hiding a bug. We should remove the check and fix the bug.

**Comment by iamrajiv** [comment] 2023-04-19 10:59
Hey @chvck, could you assist me in identifying the root cause of the bug that's being masked by the atomic operation used to prevent the bootstrap function from being executed twice? Additionally, could you please let me know if the code for the bootstrap function can be found here: https://github.com/couchbase/gocbcorex/blob/9b3be4685cfe91946c885621921dd42945a98b80/configbootstrap_http.go?

**Comment by chvck** [comment] 2023-04-19 11:14
Hi @iamrajiv the bootstrap logic is actually at https://github.com/couchbase/gocbcorex/blob/master/memdx/op_bootstrap.go however, there is already a PR open for this.

**Comment by iamrajiv** [comment] 2023-04-19 11:16
Oh ok, I got it. Thank you, @chvck

**Comment by brett19** [comment] 2023-05-18 20:09
This has been resolved by the refactoring of our bootstrap operation pipelining.

**Closed by brett19** 2023-05-18 20:09 UTC
