### ISSUE TITLE
Fix Collection Resolution data race

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#39] opened 2023-03-09 03:52 UTC
```
WARNING: DATA RACE
Write at 0x00c00040a38c by goroutine 214:
  github.com/couchbase/gocbcorex.TestCollectionsManagerCancelContextAllOps.func1()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached_test.go:492 +0xe4
  github.com/couchbase/gocbcorex.(*CollectionResolverMock).ResolveCollectionID()
      /home/brett/stellar-gateway/contrib/gocbcorex/mock_collectionresolver_test.go:134 +0x2c3
  github.com/couchbase/gocbcorex.(*CollectionResolverCached).resolveCollectionThread()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached.go:150 +0x22b
  github.com/couchbase/gocbcorex.(*CollectionResolverCached).resolveCollectionIDSlow.func1()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached.go:211 +0x99

Previous read at 0x00c00040a38c by goroutine 203:
  github.com/couchbase/gocbcorex.TestCollectionsManagerCancelContextAllOps()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached_test.go:528 +0x6bc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47

Goroutine 214 (running) created at:
  github.com/couchbase/gocbcorex.(*CollectionResolverCached).resolveCollectionIDSlow()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached.go:211 +0x4bd
  github.com/couchbase/gocbcorex.(*CollectionResolverCached).ResolveCollectionID()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached.go:113 +0x168
  github.com/couchbase/gocbcorex.TestCollectionsManagerCancelContextAllOps.func2()
      /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached_test.go:517 +0xba

Goroutine 203 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1493 +0x75d
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1846 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1844 +0x7ec
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1726 +0xa84
  github.com/couchbase/gocbcorex/testutils.SetupTests()
      /home/brett/stellar-gateway/contrib/gocbcorex/testutils/utils.go:117 +0x684
  github.com/couchbase/gocbcorex.TestMain()
      /home/brett/stellar-gateway/contrib/gocbcorex/testmain_test.go:11 +0x324
  main.main()
      _testmain.go:183 +0x31f
==================
--- FAIL: TestCollectionsManagerCancelContextAllOps (0.00s)
    collectionresolver_cached_test.go:528:
                Error Trace:    /home/brett/stellar-gateway/contrib/gocbcorex/collectionresolver_cached_test.go:528
                Error:          Not equal:
                                expected: 0x1
                                actual  : 0x0
                Test:           TestCollectionsManagerCancelContextAllOps
    testing.go:1319: race detected during execution of test
```

**Comment by chvck** [comment] 2023-03-14 11:22
I can't repro this but I think it's actually a race in the test itself.

**Comment by chvck** [comment] 2023-10-04 15:09
Closing this as cannot reproduce.

**Closed by chvck** 2023-10-04 15:09 UTC
